name: "setup task environment"

runs:
  using: "composite"
  steps:
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      shell: bash
      run: yarn install

    - name: Generate prisma client
      shell: bash
      run: yarn setup

    - uses: nrwl/nx-set-shas@v2.2.5
