name: Production Deploy
on:
  push:
    branches:
      - main
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  FLY_REGION: fra
  FLY_ORG: open-decision

jobs:
  api:
    name: Deploy api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup environment
        uses: ./.github/actions/setup
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: yarn nx deploy api

  builder:
    name: Deploy builder
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: yarn add global vercel@latest

      - name: Deploy to Vercel Action
        uses: PhilGarb/deploy-to-vercel-action@v1.9.8
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
