name: Fly Deploy
on:
  push:
    branches:
      - main
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  FLY_REGION: fra
  FLY_ORG: open-decision

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: latest
          run_install: true
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "pnpm"
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: pnpm nx deploy renderer-app
